[package]
name = "iced"
version = "0.1.0-alpha"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A GUI runtime, heavily inspired by Elm."
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced"
readme = "README.md"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = ["winit"]

[dependencies]
stretch = "0.2"
twox-hash = "1.5"

# Enable to obtain conversion traits
winit = { version = "0.20.0-alpha3", optional = true }

[dev-dependencies]
# A personal `ggez` fork that introduces a `FontCache` type to measure text
# efficiently and fixes HiDPI issues.
ggez = { version = "0.5", git = "https://github.com/hecrj/ggez.git" }
env_logger = "0.6"
