[package]
name = "iced"
version = "0.1.0-alpha"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A GUI runtime, heavily inspired by Elm."
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced"
readme = "README.md"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[dependencies]
stretch = "0.2"
nalgebra = "0.18"
twox-hash = "1.5"

[dev-dependencies]
ggez = { version = "0.5", git = "https://github.com/hecrj/ggez" }
