blank_issues_enabled: false
contact_links:
  - name: I have a question / suggestion / idea
    url: https://github.com/iced-rs/iced/discussions/new
    about: Use GitHub Discussions if you have any questions or suggestions or want to discuss any ideas.
  - name: I want to chat with other users of the library
    url: https://discord.com/invite/3xZJ65GAhd
    about: Feel free to hang out with the community in the Discord Server!
