name: Build
on:
  push:
    branches:
      - master
jobs:
  todos_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - name: Install xcb libraries
      run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - uses: actions/checkout@master
    - name: Enable Link Time Optimizations
      run: |
        echo "[profile.release]" >> Cargo.toml
        echo "lto = true" >> Cargo.toml
    - name: Add .deb package metadata
      run: |
        echo '[package.metadata.deb.variants.todos]' >> Cargo.toml
        echo 'extended-description = "A simple Todo app built with Iced, a cross-platform GUI library for Rust"' >> Cargo.toml
        echo 'assets = [' >> Cargo.toml
        echo '["target/release/examples/todos", "usr/bin/iced-todos", "755"],' >> Cargo.toml
        echo '["iced-todos.desktop", "usr/share/applications/", "644"]' >> Cargo.toml
        echo ']' >> Cargo.toml
    - name: Create .desktop file
      run: |
        echo '[Desktop Entry]' >> iced-todos.desktop
        echo 'Name=Todos - Iced' >> iced-todos.desktop
        echo 'Exec=iced-todos' >> iced-todos.desktop
        echo 'Type=Application' >> iced-todos.desktop
    - name: Build todos binary
      run: cargo build --verbose --release --example todos
    - name: Archive todos binary
      uses: actions/upload-artifact@v1
      with:
        name: todos-x86_64-unknown-linux-gnu
        path: target/release/examples/todos
    - name: Build todos .deb package
      run: cargo deb --variant todos -- --example todos
    - name: Rename todos .deb package
      run: mv target/debian/*.deb target/debian/iced_todos-x86_64-debian-linux-gnu.deb
    - name: Archive todos .deb package
      uses: actions/upload-artifact@v1
      with:
        name: todos-x86_64-debian-linux-gnu
        path: target/debian/iced_todos-x86_64-debian-linux-gnu.deb

  todos_windows:
    runs-on: windows-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Enable Link Time Optimizations
      run: |
        echo "[profile.release]" >> Cargo.toml
        echo "lto = true" >> Cargo.toml
    - name: Enable static CRT linkage
      run: |
        mkdir .cargo
        echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
        echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
    - name: Build todos binary
      run: cargo build --verbose --release --example todos
    - name: Archive todos binary
      uses: actions/upload-artifact@v1
      with:
        name: todos-x86_64-pc-windows-msvc
        path: target/release/examples/todos.exe

  todos_macos:
    runs-on: macOS-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Enable Link Time Optimizations
      run: |
        echo "[profile.release]" >> Cargo.toml
        echo "lto = true" >> Cargo.toml
    - name: Build todos binary
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.14
      run: cargo build --verbose --release --example todos
    - name: Archive todos binary
      uses: actions/upload-artifact@v1
      with:
        name: todos-x86_64-apple-darwin
        path: target/release/examples/todos
