name: Integration
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
        targets: ${{ matrix.targets }}
    - uses: actions/checkout@master
    - name: Run tests
      run: |
        cargo test --verbose --all
        cargo test --verbose --all --all-features
