name: Test
on: [push, pull_request]
jobs:
  all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Install xcb libraries
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Run tests
      run: |
        cargo test --verbose --all
        cargo test --verbose --all --all-features
